#!/bin/sh

TMP=''
LIB="/run/initramfs/lib/livekitlib"
CFG="/run/initramfs/lib/config"

while getopts "t:l:c:?" arg; do
    case $arg in
        t) TMP="$OPTARG" ;;
        l) LIB="$OPTARG" ;;
        c) CFG="$OPTARG" ;;
        ?)
            echo "Usage:"
            echo "  $0 [-t tmp] [-l livekitlib] module packages..."
            echo
            echo "tmp: Directory for temporary workspace (defaults to a"
            echo "  random directory in /tmp)"
            echo "livekitlib: Location of Linux Live library script"
            echo "  (default $LIB)"
            echo "module: Name of module to create. If no directory specified,"
            echo "  places it in the boot media on the current live system"
            echo "packages: Slackware packages to make into the given module"
            exit
            ;;
    esac
done

shift $((OPTIND - 1))

if [ "$2" = "" ]; then
    exec "$0" '-?'
fi

. "$CFG" || exit 1
. "$LIB" || exit 1

if [ "$TMP" = "" ]; then
    TMP=`mktemp -t -d pkg2bundle.XXXXXXXX`
else
    TMP="$TMP/pkg2bundle"
    rm -rf "$TMP" || exit 1
    mkdir -p "$TMP" || exit 1
fi

fs=`df --output=fstype "$TMP" | tail -1`
if [ "$fs" = "overlay" ]; then
	echo "The given temporary directory is on an overlayfs filesystem."
	echo "overlayfs can't overlay over itself, so we're going to mount"
	echo "a ramdrive and use that instead. This may fail if you're"
	echo "building a very large module."
	mount -t tmpfs tmpfs "$TMP" || exit 1
	TMPFS=1
fi


module="$1"

# Add an extension if not provided
base="`basename "$module"`"
stub="${base%.*}"
if [ "$stub" = "$base" ]; then
    module="$module.$BEXT"
fi

# Append boot media directory if no directory given
if [ "`basename "$module"`" = "$module" ]; then
    module="/run/initramfs/memory/data/slakresq/$module"
fi


shift

echo "Setting up staging area in $TMP..."

(
    mkdir "$TMP/pkgs"
    cp "$@" "$TMP/pkgs" || exit 1

    echo "Creating overlay filesystem..."
    mkdir -p "$TMP/diff/data" || exit 1
    mkdir -p "$TMP/diff/work" || exit 1
    mkdir "$TMP/ovl" || exit 1

    mount -t overlay -o "lowerdir=/,upperdir=$TMP/diff/data,workdir=$TMP/diff/work" \
        overlay "$TMP/ovl" || exit 1
    (
        mkdir -p "$TMP/ovl/mnt/pkg2bundle" || exit 1
        mount --bind "$TMP/pkgs" "$TMP/ovl/mnt/pkg2bundle"
        chroot "$TMP/ovl" /sbin/installpkg --terse /mnt/pkg2bundle/* || FAIL=1
        umount "$TMP/ovl/mnt/pkg2bundle" || FAIL=1
        rmdir "$TMP/ovl/mnt/pkg2bundle" || exit 1
        exit $FAIL
    ) || FAIL=1
    umount "$TMP/ovl" || exit 1
    test $FAIL && exit 1
    create_bundle "$TMP/diff/data" "$module" || exit 1
)

if [ $? != 0 ]; then
    echo "Temporary files remain in $TMP"
    exit 1
fi

echo "Cleaning up..."
if [ $TMPFS ]; then
	umount "$TMP"
fi
rm -rf "$TMP"

