#!/bin/sh

main()
{
    while getopts "o:dp" opt; do
        case "$opt" in
            o) export ORIG="$OPTARG";;
            d) export DEBUG=1;;
            *) exit 1 ;;
        esac
    done
    shift $((OPTIND - 1))
    if [ $DEBUG ]; then
        echo "$ORIG"
        echo "$DEBUG"
        echo "$*"
        dbgecho='echo'
        redir=/dev/stdout
    else
        dbgecho='true'
        redir=/dev/null
    fi

    if [ "$1" = "" ]; then
        if [ "$ORIG" == "" ]; then
            echo "Recreating patch tree..."
            rm -rf trees/99-patches
        fi
        find patches -name "*.srp" |
            while read patch; do
                applypatch "$patch" || exit 1
            done
        true
    else
        for patch in "$@"; do
            applypatch "$patch"
        done
    fi
}

# Apply a patch file
# $1: Patch file

applypatch() {
    local patchfile="$1"
    local patchdir="`dirname "$patchfile"`"

    $dbgecho "Examining $patchfile"

    TMP="`mktemp -dt srpatch.$$.XXXXXXXX`" || exit 1
    trap cleanup EXIT

    cutpatch "$patchfile" "$TMP"
    cut=$?
    
    # Path to patch header
    local head
    # Path to patch contents
    local patch

    if [ $cut = 0 ]; then
        # echo "Cut."
        export head="$TMP/head"
        export patch="$TMP/patch"
    else
        # echo "External."
        export head="$patchfile"
        export patch=/dev/null
    fi


    local tree
    local path
    local dir
    local from
    local replace
    local dest=patches
    local external
    local type
    local chmod
    local owner
    local group
    local cond

    local base="`basename "$patchfile"`"
    base="${base%.*}"

    . "$head"

    if [ "$dest" = orig -a "$tree" = "" ]; then
        echo "$1: dest=orig requires tree to be set" 1>&2
        exit 1
    fi

    if [ "$ORIG" != "" ]; then
        if [ "$dest" != "orig" -o "$tree" != "$ORIG" ]; then
            $dbgecho "Skipping, not the target tree" 1>&2
            return 0
        fi
    else
        if [ "$dest" != "patches" ]; then
            $dbgecho "Skipping, not the target tree" 1>&2
            return 0
        fi
    fi

    if [ "$tree" != 'base' -a "$tree" != '' -a \
        ! -e "trees/$tree" ]; then
        $dbgecho "Skipping, tree $tree does not exist" 1>&2
        return
    fi

    # At this point we should be decided that we *are* applying this patch.
    echo "$1"

    if [ "$path$dir" = "" ]; then
        echo "path or dir is required" 1>&2
        exit 1
    fi


    if [ "$external" != "" ]; then
        patch="$patchdir/$external"
    fi

    if [ "$dir" != "" ]; then
        path="$dir/$base"
    fi

    head="`realpath "$head"`"
    patch="`realpath "$patch"`"

    # Location of original file, relative to generated root
    orig="$path"
    if [ "$from" != "" ]; then
        orig="$from"
    fi
    if [ "$replace" != "" ]; then
        orig="$replace"
    fi

    # Path to the given tree, relatve to slakresq build tree
    local sourceroot
    if [ "$tree" != "" ]; then
        if [ "$tree" = "base" ]; then
            sourceroot="$tree"
        else
            sourceroot="trees/$tree"
        fi
        sourceroot="`realpath "$sourceroot"`"
    fi
    local sourcepath="$sourceroot/$orig"
    local origpath="$sourcepath"

    local destroot="trees/99-patches"
    if [ "$dest" = "orig" -a -f "$sourcepath" ]; then
        destroot="$sourceroot"
        if [ "$from$replace" = "" ]; then
            cp "$sourcepath" "$TMP/orig"
            sourcepath="$TMP/orig"
        fi

    fi
    destroot="`realpath "$destroot"`"


    local destpath="$destroot/$path"
    # If a patched file already exists in 99-patches, copy it to temp
    # as the new source. (Patching a patch)
    if [ "$dest" = "patches" -a -f "$destpath" ]; then
        if [ "$from$replace" = "" ]; then
            cp "$destpath" "$TMP/orig"
            sourcepath="$TMP/orig"
        else
            echo "Patch conflicts with previous patch" 1>&2
        fi

    fi

    if [ "$cond" ]; then
        $dbgecho "Conditional: $cond" 1>&2
        sh -c "$cond" /dev/null "$sourcepath"
        if [ $? != 0 ]; then
            $dbgecho "Skipped; conditional not met"
            return
        fi
    fi

    if [ $DEBUG ]; then
        echo "Patch header: $head"
        echo "Patch body: $patch"
        echo "File base: $base"
        echo "Target path: $path"
        echo "Source path: $orig"
        echo "Physical source root: $sourceroot"
        echo "Physical source path: $sourcepath"
        echo "Physical (original) source path: $origpath"
        echo "Physical target root: $destroot"
        echo "Physical target path: $destpath"
    fi
    
    mkdir -p "`dirname "$destpath"`"

    (case "$type" in
        patch)
            patch "$sourcepath" "$patch" -o "$destpath" || exit 1
            ;;
        new) 
            cp "$patch" "$destpath" || exit 1
            ;;
        insert|prepend)
            if [ "$before$after" != "" ]; then
                local match="$before$after"
                local line="`grep -m 1 -n -E "$match" "$sourcepath" |
                    cut -d : -f 1`" || exit 1
                if [ "$after" != "" ]; then
                    line=$((line + 1))
                fi
            elif [ "$skip" != "" ]; then
                local line="`grep -n -m 1 -v -E "$skip" "$sourcepath" |
                    cut -d : -f 1`" || exit 1
            else
                line=1
            fi
            (head -n "$((line - 1))" "$sourcepath"
            cat "$patch"
            tail -n "+$line" $sourcepath) > "$destpath"

            ;;
        append)
            cat "$sourcepath" "$patch" > "$destpath" || exit 1
            ;;
        copy)
            cp -a "$sourcepath" "$destpath" || exit 1
            ;;
        tar)
            mkdir -p "$destpath"
            tar -C "$destpath" -x -f "$patch" || exit 1
            ;;
        delete)
            if [ "$dest" = "orig" ]; then
                rm -rf "$origpath" || exit 1
            else
                mknod "$destpath" c 0 0 || exit 1
            fi
            ;;
        link)
            ln -s "$from" "$destpath" || exit 1
            ;;
        script)
            (cd "$patchdir"
            chmod u+x "$patch"
            "$patch" $sourcepath $destpath $head) || exit 1
            ;;
        *)
            echo "Unknown patch type: $type" 1>&2
            exit 1
            ;;

    esac) > $redir
    if [ $? != 0 ]; then
        echo "Patch failed." 1>&2
        exit 1
    fi

    if [ "$chmod" != "" ]; then
        chmod "$chmod" "$destpath" || exit 1
    fi
    if [ "$owner" != "" ]; then
        chown "$owner" "$destpath" || exit 1
    fi
    if [ "$group" != "" ]; then
        chgrp "$group" "$destpath" || exit 1
    fi

}

cleanup() {
    # echo "Removing temp files... $TMP"
    rm -rf "$TMP"
}

# Cut the patch in the file into the patch header and the contents.
# Pieces will be placed in $1/head and $1/patch.
#
# If no contents are present, returns 1 and doesn't split
#
# $1: Patch file
# $2: Temp directory
cutpatch() {
    grep -Eq '^-+$' "$1" || return 1
    (
    while read line; do
        if [ "${line##*-}" = "" ]; then
            break
        fi
        echo $line >> "$2/head"
    done

    cat >> "$2/patch"
    ) < "$1"
}

main "$@"
