#!/bin/bash

# Prepare to build the Linux Live base image

. live/config || exit 1
. config || exit 1
. tools/srqlib || exit 1

while getopts "i" opt; do
    if [ $opt = i ]; then
        # The LLK build script recognizes this if set
        export SKIPCOREMOD=1
    elif [ $opt = '?' ]; then
        echo "Usage: $0 [-i]"
        echo "  -i: Only build the initramfs"
        exit 1
    fi
done

checkroot || exit 1

echo "Building the live boot image..."

# If we have a bootinfo.txt that's newer than the one in live, copy it over

if [ bootinfo.txt -nt live/bootinfo.txt ]; then
    cp bootinfo.txt live/bootinfo.txt || exit 1
fi

(
# Exit the subshell if interrupted, so cleanup can occur
trap "exit 1" INT TERM HUP

# Make the Linux Live script available in the base filesystem
mkdir -p base/live || exit 1
mount --bind live base/live || exit 1

# Mount system filesystems in base filesystem
mount -t devtmpfs devtmpfs base/dev || exit 1
mount -t devpts devpts base/dev/pts || exit 1
mount -t proc proc base/proc || exit 1

# Cleanup any old builds
rm -rf base/tmp/$LIVEKITNAME-data-*

# Build the system
chroot base /live/build || exit 1

# Copy new build into target
mkdir -p target || exit 1
cp -a base/tmp/$LIVEKITNAME-data-*/* target || exit 1

# Move EFI bootloader to appropriate place
rm -rf target/EFI
mv target/$LIVEKITNAME/boot/EFI target || exit 1
)
result=$?

# Cleanup
umount base/dev/pts base/dev base/proc base/live || exit 1

exit $result

