#!/bin/bash

while getopts 'niutTma?' arg; do
    case $arg in
        i) INSTALL=1;;
        u) UPDATES=1;;
        t) TARGET=1;;
        T) TREES=1;;
        m) TEMP=1;;
        b) BASE=1;;
        n) ECHO='echo';;
        a)
            INSTALL=1
            UPDATES=1
            TARGET=1
            TREES=1
            TEMP=1
            BASE=1
            ;;

        '?')
            echo "Usage: `basename $0` [-iutTma]"
            echo ''
            echo '-m    Delete temporary folders'
            echo '-t    Delete target folder'
            echo '-T    Delete bundle trees'
            echo '-b    Delete base folder'
            echo '-u    Delete updates folder'
            echo '-i    Delete install disksets'
            echo '-a    Delete all of the above'
            echo '-n    Dry run: Display what would be done'
            exit
            ;;
    esac
done

if [ ! "$1" ]; then
    exec $0 -?
fi

if [ $INSTALL ]; then
    $ECHO rm -rf install initrd.img
fi

if [ $UPDATES ]; then
    $ECHO rm -rf updates
fi

if [ $TARGET ]; then
    $ECHO rm -rf target
fi

if [ $TEMP ]; then
    $ECHO rm -rf diff instenv merged
fi

if [ $BASE ]; then
    $ECHO rm -rf base
fi

if [ $TREES ]; then
    $ECHO rm -rf `find trees/ -mindepth 1 -maxdepth 1 \! -name 99-patches`
fi
