#!/bin/bash

. live/config || exit 1
. config || exit 1
. tools/srqlib || exit 1


if [ x$1 = x ]; then
    echo "Usage: $0 bundle_name [diskset...]"
    exit
fi

checkroot || exit 1

bundle=$1
shift
disksets="$*"

if [ "$disksets" = "" ]; then
    disksets="${BUNDLE[$bundle]}"
fi

if [ "$disksets" = "" ]; then
    echo No disksets specified
    exit 1
fi

echo "Setting up install environment..."

# Create the diff directory if necessary, and clear the work directory
rm -rf diff/work || exit 1
mkdir -p diff/data diff/work merged || exit 1

(
# Exit the subshell if interrupted, so cleanup can occur
trap "exit 1" INT TERM HUP

# Mount the overlay
mount -t overlay -o lowerdir=base,upperdir=diff/data,workdir=diff/work overlay merged || exit 1

# Mount stuff the environment needs
mount -t proc proc merged/proc || exit 1
mount -t devtmpfs devtmpfs merged/dev || exit 1
mount -t devpts devpts merged/dev/pts || exit 1

# Make install folder available in build environment
mount --bind install merged/mnt/hd || exit 1

for disk in $disksets; do
    echo "Installing diskset $disk"
    chroot merged /sbin/installpkg --terse /mnt/hd/$disk/*.t?z || exit 1
done

rm -rf trees/$bundle || exit 1
mv diff/data trees/$bundle
)
result=$?

echo "Cleaning up..."

# Unmount everything
umount merged/dev/pts merged/dev merged/proc merged/mnt/hd merged || exit 1

exit $result

