#!/bin/bash

. config || exit 1

disksets="$CORE_DISKSETS ${BUNDLE[@]}"

mkdir -p install || exit 1

echo $disksets

for diskset in $disksets; do
    if [ ! -d install/$diskset ]; then
        echo "Downloading diskset $diskset..."
        lftp -c mirror -ev "$MIRROR/$diskset" install/$diskset || exit 1
    fi
done

if [ ! -e initrd.img ]; then
	echo "Downloading Slackware installer image..."
	mirrorbase="`dirname $MIRROR`"
	lftp -c get "$mirrorbase/isolinux/initrd.img" || exit 1
fi
