#!/bin/bash

. config || exit 1

disksets="$CORE_DISKSETS ${BUNDLE[@]}"

mkdir -p install || exit 1

path="$MIRROR/$VERSION"

for diskset in $disksets; do
    if [ ! -d install/$diskset ]; then
        echo "Downloading diskset $diskset..."
        tools/ftpget mirror "$path/$diskset" install/$diskset || exit 1
    fi
done

if [ ! -e initrd.img ]; then
	echo "Downloading Slackware installer image..."
	mirrorbase="`dirname $path`"
	tools/ftpget get "$mirrorbase/isolinux/initrd.img" || exit 1
fi
