#!/bin/bash

# Download updates from the configured mirror

. config || exit 1

mirrorbase="`dirname $MIRROR/$VERSION`"

mkdir -p updates || exit 1

echo "Checking for updates"
tools/ftpget mirror "$mirrorbase/patches/packages" updates || exit 1
