#!/bin/bash

# Download updates from the configured mirror

. tools/srqlib || exit 1

disksetpath="`disksetpath`"
mirrorbase="`dirname $MIRROR/"$disksetpath"`"

mkdir -p updates || exit 1

echo "Checking for updates"
tools/ftpget mirror "$mirrorbase/patches/packages" updates || exit 1
