#!/bin/bash

. config || exit 1

if [ $FETCHINSTALL ]; then
    tools/fetchinstall || exit 1
else
    if [ ! -d install/a ]; then
        echo "No disksets are present in the install/ directory. Either populate it"
        echo "from the Slackware mirrors, or enable FETCHINSTALL in the config"
        echo "to download it automatically"
        exit 1
    fi
fi

if [ $FETCHUPDATES ]; then
    tools/fetchupdates || exit 1
fi

if [ $INSTALLUPDATES ]; then
    if [ ! -d updates ]; then
        echo "Requested updates, but no updates present. Skipped."
    else
        echo "Installing any pending updates..."
        tools/updatepkgs || exit 1
    fi
fi

tools/mkbase || exit 1
tools/buildlive || exit 1
tools/prepbundles || exit 1
tools/squashbundle || exit 1

echo "Done."


