#!/bin/bash

# Install a base Slackware system into the base/ directory

. config

if [ `whoami` != root ]; then
    echo "Error: We are not root"
    exit 1
fi
 
echo "Installing base system into base ..."

DISKSETS="$CORE_DISKSETS"

if [ x$1 != x ]; then
    DISKSETS="$*"
fi

# Start from scratch
echo "Cleaning up old files..."
rm -rf base || exit 1
mkdir base || exit 1

for diskset in $DISKSETS; do
    echo "Installing diskset $diskset..."
    installpkg --root base --terse install/$diskset/*.t?z || exit 1
done

if [ "x$SUPPORT_PKGS" != x ]; then
    echo "Installing support packages for Linux Live Kit..."
    for pkg in $SUPPORT_PKGS; do
        installpkg --root base --terse install/*/$pkg-*.t?z || exit 1
    done
fi
chroot base /sbin/ldconfig

echo Done.
