#!/bin/bash

# Make the bundle for the given trees, default everything

. config || exit 1
. live/config || exit 1
. live/livekitlib || exit 1
. tools/srqlib || exit 1

checkroot || exit 1

bundles="$*"
if [ x$bundles = x ]; then
    bundles="`ls trees`"
fi

for bundle in $bundles; do
    echo "Compressing bundle $bundle..."
    (
    cd trees/$bundle || exit 1
    rm -f ../../target/$LIVEKITNAME/"$bundle.$BEXT"
    create_bundle . ../../target/$LIVEKITNAME/"$bundle.$BEXT"
    )
done

