#!/bin/bash

# Make the bundle for the given trees, default everything

. config
. live/config

bundles="$*"
if [ x$bundles = x ]; then
    bundles="`ls trees`"
fi

for bundle in $bundles; do
(
cd trees/$bundle || exit 1
mksquashfs . ../../target/$LIVEKITNAME/"$bundle.srq" \
    -comp xz -b 1024K -Xbcj x86 -always-use-fragments
)
done

