#!/bin/sh

LIB="/run/initramfs/lib/livekitlib"
CFG="/run/initramfs/lib/config"

while getopts "l:c:n?" arg; do
    case $arg in
        l) LIB="$OPTARG" ;;
        c) CFG="$OPTARG" ;;
        n) NAME=1 ;;
        ?)
            echo "Usage:"
            echo "  $0 [-n] [-l livekitlib] [-c cfg] target source_dir"
            echo
            echo "livekitlib: Location of Linux Live library script"
            echo "  (default $LIB)"
            echo "config: Location of Linux Live configuration file"
            echo "  (default $CFG)"
            echo "source_dir: Directory to create module out of"
            echo "target: Module file to create"
            echo
            echo "-n: Generate a bundle name but don't build anything"
            exit
            ;;
    esac
done

shift $((OPTIND - 1))

if [ "$1" = "" ]; then
    exec "$0" '-?'
fi

if [ "$2" = "" -a ! "$NAME" ]; then
    exec "$0" '-?'
fi

. "$CFG" || exit 1
. "$LIB" || exit 1

module="$1"

# Add an extension if not provided
base="`basename "$module"`"
stub="${base%.*}"
if [ "$stub" = "$base" ]; then
    module="$module.$BEXT"
fi

# Append boot media directory if no directory given
if [ "`basename "$module"`" = "$module" ]; then
    module="/run/initramfs/memory/data/$LIVEKITNAME/$module"
fi

# Prepend a number (100) if none given
basename="`basename $module`"
if [ "${basename#[0-9]}" = "$basename" ]; then
    module="`dirname $module`/100-$basename"
fi

if [ $NAME ]; then
    echo "$module"
    exit
fi

create_bundle "$2" "$module"
